### ISSUE TITLE
How to stop this strange behavior?

### ISSUE THREAD

**Issue by in-in** [brackets-userland/brackets-git#1029]
When I start a new project, it creates a .gitignore and makes first commit (_.gitignore created by brackets-git extension_)
How to stop it?

---

Brackets: Release 1.3 experimental build 1.3.0-16022 (release cd0a6aae5) 
Git: 2.4.0
Brackets Git: 0.14.25
Linux Mint 17

**Comment by sbruchmann** [comment]
+1

I would really like to see an option for disabling this behaviour.
