### ISSUE TITLE
Misspelled word in Git Settings

### ISSUE THREAD

**Issue by brazucaz** [brackets-userland/brackets-git#1341]
First of all, great extension, this is a really helpful, and I have had no technical issues at all. So, thank you.

Browsing through your extension I came across some misspelled words - nothing major; just thought this might be helpful.

It's on your Git Settings, at the very bottom under Advanced features.
![capture](https://user-images.githubusercontent.com/17728473/33786012-6decbbf8-dc35-11e7-91a3-50c0aac0680d.PNG)

You have on there:

> This features are not recommended for basic Git users as they may cause you to lose code that has been already commited if used inproperly. Use with caution.

Where, really it would be

> These (plural)

> Committed

and 

> Improperly

Now, I would suggest also rephrasing that a bit, for instance:

> These features are not recommended for basic Git users. They may cause you to lose code that has already been committed if used improperly. Use with caution.

Cheers,

brazucaz

**Comment by Peter-Burns** [comment]
Working on this
