### ISSUE TITLE
Close & Re-open to save again

### ISSUE THREAD

**Issue by T3chArmy** [brackets-userland/brackets-git#909]
For some reason everytime I save my index.html file I have to close it and re-open it in order to save it again.

---

_Brackets 1.1.0-15558 (win), Git 1.9.4.msysgit.2 & Brackets-Git 0.14.10_

```
#1. Error reloading contents of C:/Users/***/Documents/Repositories/transport_form/index.html
#2. TypeError: Cannot read property 'search' of undefined
```

**Comment by zaggino** [comment]
How does this relate to Brackets-Git?

**Comment by T3charmy** [comment]
if I uninstall Brackets-Git everything works fine. soon as I reinstall it, it starts doing it again.

**Comment by T3charmy** [comment]
Just did some more through testing.... It's only happening on this single repository.. more specifically this single fine... not sure why.

**Comment by macbookandrew** [comment]
@T3charmy Do you happen to have the [Brackets Code Folding](https://github.com/thehogfather/brackets-code-folding) extension also installed?

@zaggino Looks like possibly a conflict with both plugins using CodeMirror? See console output screenshot: 
![screen shot 2015-02-12 at 1 42 08 pm](https://cloud.githubusercontent.com/assets/784333/6174500/26a25be4-b2bd-11e4-882f-875416cb244b.png)

Disabling either plugin solves the issue.

**Comment by zaggino** [comment]
Does this happen when you disable Git gutters in the settings?

**Comment by macbookandrew** [comment]
That seems to fix the issue

**Comment by zaggino** [comment]
Ok, I'll take a look what's wrong with the gutters. Thanks

**Comment by macbookandrew** [comment]
@zaggino So…still having the issue, even with the gutters disabled. Here’s the full console log:
![screen shot 2015-02-12 at 8 37 21 pm](https://cloud.githubusercontent.com/assets/784333/6180726/09b76418-b2f7-11e4-9645-80c337e431d2.png)

**Comment by macbookandrew** [comment]
The author of the code-folding extension [gave me an update](https://github.com/thehogfather/brackets-code-folding/issues/119#issuecomment-74259522) that fixes the console errors with his plugin, and that seems to fix the issues here too.

**Comment by thehogfather** [comment]
There was indeed a bug in code-folding that threw an error in code mirror. This was a result of accessing line number that is out of range of the current editor. I suspect the actual error has nothing to do with the git-extension but @T3charmy should do some more tests to try to reproduce the original issue.

**Comment by T3charmy** [comment]
@macbookandrew I did happen to be running code folding. Just downloaded the update of that, Will let you know after I test more.

**Comment by T3charmy** [comment]
So far it seems ok. I'm gonna do more extensive testing and see if everything is ok when I actually go to code later tonight.
