### ISSUE TITLE
Feature Request: Auto Push on commit

### ISSUE THREAD

**Issue by T3chArmy** [brackets-userland/brackets-git#964]
One feature I think would be really useful to have is the ability to automatically push code after a commit. I've seen this feature in other things such as SourceTree, and it's a really nice feature... I'm so used to SourceTree auto pushing all my commits I forgot to push code when I left for work this morning.

---

_Brackets 1.2.0-15697 (win), Git 1.9.5.msysgit.0 & Brackets-Git 0.14.17_

**Comment by ignaciohita** [comment]
:+1:
